# Dependency Review Action
#
# Scans dependency manifest changes in pull requests for known vulnerabilities.
# Blocks PRs introducing vulnerable packages if the workflow is required.
#
# Source: https://github.com/actions/dependency-review-action
# Docs: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement

name: "Dependency Review"

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write # Required for PR summary comments; remove if unused.

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Dependency Review
        uses: actions/dependency-review-action@v4
