name: Dependency Review

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          # Fail on vulnerabilities of moderate severity or higher
          fail-on-severity: moderate
          # Allow GHSA IDs to be ignored
          # Example: allow-ghsa: ["GHSA-xxxx-xxxx-xxxx"]
          # Fail if dependencies have incompatible licenses
          deny-licenses: "GPL-3.0, AGPL-3.0, LGPL-3.0, CC-BY-NC-1.0"
          # Comment on PR with review summary
          comment-summary-in-pr: always
