name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  actions: write

jobs:
  test:
    name: Test with Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # Checkout repository code
      - uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run security audit
      - name: Run npm audit
        run: npm audit --audit-level=moderate
        continue-on-error: false

      # Generate Prisma client
      - name: Generate Prisma client
        run: npm run prisma:generate

      # Build package (includes type checking)
      - name: Build package
        run: npm run build

      # Run tests
      - name: Run tests
        run: npm test

      # Upload test coverage reports
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
