name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    name: Test with Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # Checkout repository code
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      # Setup Node.js environment
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Install dependencies (with scripts disabled for security)
      - name: Install dependencies
        run: npm ci --ignore-scripts

      # Run security audit
      - name: Run npm audit
        run: npm audit --audit-level=moderate
        continue-on-error: false

      # Lint source files
      - name: Run lint
        run: npm run lint

      # Generate Prisma client
      - name: Generate Prisma client
        run: npm run prisma:generate

      # Build package (includes type checking)
      - name: Build package
        run: npm run build

      # Run tests
      - name: Run tests
        run: npm test

      # Upload test coverage reports
      - name: Upload coverage reports
        uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457 # v3
        with:
          fail_ci_if_error: false
